# Generated by Django 5.1.6 on 2025-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnhub", "0002_alter_feedback_student_alter_course_teacher_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
