# Generated by Django 5.1.6 on 2025-02-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnhub", "0004_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256, unique=True)),
                ("image", models.FileField(upload_to="")),
                ("thumbnail", models.FileField(null=True, upload_to="")),
            ],
        ),
    ]
