# Generated by Django 5.1.6 on 2025-03-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnhub", "0008_statusupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusupdate",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
