# Generated by Django 5.1.6 on 2025-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnhub", "0010_alter_statusupdate_image_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
