# Generated by Django 5.1.6 on 2025-03-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnhub", "0013_rename_created_at_alert_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=255)),
                ("sender", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
