# Generated by Django 5.1.6 on 2025-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnhub", "0014_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusupdate",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
